### ISSUE TITLE
'www.hs.fi' failes to fetch info

### ISSUE THREAD

**Issue by OzQu** [pauljohncleary/url-info-scraper#1]
I pass url 'www.hs.fi' to this and node crashes with following output:

/node_modules/url-info-scraper/index.js:40
        if (responseObject.mime.substring(1,11) === 'pplication' )  {
                               ^
TypeError: Cannot read property 'substring' of undefined
    at Request._callback (/node_modules/url-info-scraper/index.js:40:32)
    at Request.self.callback (/node_modules/url-info-scraper/node_modules/request/request.js:197:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/node_modules/url-info-scraper/node_modules/request/request.js:1050:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/node_modules/url-info-scraper/node_modules/request/request.js:996:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by pauljohncleary** [comment]
Thanks for the report. Fixed here: https://github.com/pauljohncleary/url-info-scraper/commit/a9ed0d47d9c67d3ac95545e143f144af88a63027
